version: '2'
services:
  gitserver:
    image: "cirocosta/gitserver-http"
    command: [ "-start", "-init" ] 
    volumes:
      - "./repositories:/var/lib/git"
    ports:
      - "1337:80"
      - "443:443"
